[book]
authors = ["uncle-sunny"]
language = "en"
src = "src"
title = "rust learning book"


[rust]
edition = "2024"

[output.html]
site-url = "/rust-book/"
git-repository-url = "https://github.com/Uncle-sunny/rust-book"
